global:
  useObjectStatus: true
  useResetQStats: false
  logLevel: INFO 
  metaprefix: ""
  pollInterval: 30s
  rediscoverInterval: 1h
  tzOffset: 0h

connection:
    queueManager: QM1
    clientConnection: false
# If a user is set, then a password must be passed somehow. It can
# be done in this file, on a command line, or (better) passed via stdin
#    user: mqadmin
#    password: passw0rd                                             
    replyQueue: SYSTEM.DEFAULT.MODEL.QUEUE

objects:
    queues:
    - APP.*
    - "!SYSTEM.*"
    - "!AMQ.*"
    - QM*
    queueSubscriptionSelector:
    - PUT
    - GET
    channels:
    - SYSTEM.*
    - TO.*
    topics:
    subscriptions:

prometheus:
  port: 9157
  metricsPath: "/metrics"
  namespace: ibmmq
